### ISSUE TITLE
code request

### ISSUE THREAD

**Issue by 0belle** [marco-rudolph/AST#1]
Hi, I am an undergraduated student, I read your article revently,  but I dont understand something. May I get the code?

**Comment by marco-rudolph** [comment]
Hello,
the code will be released in a few weeks when I am back in office. Sorry for the delay.

Best,
Marco

**Comment by 0belle** [comment]
Hello, 
I have a question about dataset, why AST work badly on dataset of cable gland、dowel and tire, I have seen dataset, but I couldn't figure it out

从 Windows 版邮件发送

发件人: marco-rudolph
发送时间: 2022年11月24日 18:38
收件人: marco-rudolph/AST
抄送: 0belle; Author
主题: Re: [marco-rudolph/AST] code request (Issue #1)

Hello,
the code will be released in a few weeks when I am back in office. Sorry for the delay.
Best,
Marco

**Comment by marco-rudolph** [comment]
Code is now online.

Best,
Marco
