### ISSUE TITLE
Teacher and NF

### ISSUE THREAD

**Issue by Leonardo0325** [marco-rudolph/AST#10]
Hello, may I ask why the teacher network uses NF? When encountering abnormal samples, how can teachers and students distinguish whether the image is abnormal?

**Comment by marco-rudolph** [comment]
Hi,
you can find the motivation in the introduction of the paper:

> The motivation is that the student can only match the outputs of the teacher on normal data since it is trained only on normal data. The distance between the outputs of student and teacher is used as an indicator of an anomaly at test-time.
> [...]
> A bijective normalizing flow [34] acts as a teacher while a conventional sequential model acts as a student. In this way, the teacher guarantees to be sensitive to changes in the input caused by anomalies. Furthermore, the usage of different architectures and thus of different sets of learnable functions enforces the effect of distant outputs for out-of-distribution samples.

Hope that helps,
Marco
