### ISSUE TITLE
false positives on inference

### ISSUE THREAD

**Issue by neo133** [marco-rudolph/AST#11]
Hi @marco-rudolph ,
Thank you for your amazing repo and super work. I really loved the paper.
I trained  AST on carpet class from MVTEC dataset and the results on bad data was extremely good , the localizations were on par with the GT.
However, when I gave a good image as input there were multiple false positives, ideally it should not be.
Could you please explain why and also if there is something I am doing wrong?

**Comment by marco-rudolph** [comment]
Hi,
thank you!
Note that each localization map is normalized according to its maximum. Thus, small scores can be highlighted.

Best,
Marco

**Comment by neo133** [comment]
i see
i will go over the implementation code once more and will reach out if i face any issue
I'm closing this as of now.
thank you

**Comment by limaodaxia** [comment]
> Hi, thank you! Note that each localization map is normalized according to its maximum. Thus, small scores can be highlighted.
> 
> Best, Marco

Hi, @marco-rudolph 
Why small scores can be highlighted?
Does normalizing here means every pixel in the localization map is processed by (pixel-min)/(max-min)? 
I can not find the code about normaling the localization map.

**Comment by limaodaxia** [comment]
And in the evaluate function, why every tensor is converted into numpy? As I know cuda with GPU can speed the process, why not use tensor?

**Comment by marco-rudolph** [comment]
> > Hi, thank you! Note that each localization map is normalized according to its maximum. Thus, small scores can be highlighted.
> > Best, Marco
> 
> Hi, @marco-rudolph Why small scores can be highlighted? Does normalizing here means every pixel in the localization map is processed by (pixel-min)/(max-min)? I can not find the code about normaling the localization map.

As matplotlib.plt.imshow maps (by default) the values to the colormap by their minimum and maximum value, small scores can be highlighted if the maximum value is small. As this happens by default, it is not included in the code of the repository. Check out https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html for the documentation of imshow.

**Comment by marco-rudolph** [comment]
> And in the evaluate function, why every tensor is converted into numpy? As I know cuda with GPU can speed the process, why not use tensor?

As evaluations functions as "roc_auc_score" take numpy array (or lists), we convert them to numpy beforehand. In our experiments, we did not observe that these operations in the evaluation caused high costs.
