### ISSUE TITLE
MVTec-AD ground_truth

### ISSUE THREAD

**Issue by YJYanJie** [marco-rudolph/AST#12]
Hello, it seems that your code did not process the MVTec-AD data set during the evaluation, and there is no folder good in ground_truth, it will report an error, how did you deal with it?

**Comment by marco-rudolph** [comment]
Please read the readme carefully.

> Set your dataset_dir in config.py. This is the directory which contains the subdirectories of the classes you want to process. It should be configured whether the datasets contains 3D scans (set use_3D_dataset in config.py). If 3D data is present (use_3D_dataset=True), the data structure from MVTec 3D-AD is assumed. It can be chosen which data domain should be used for detection (set mode in config.py). If the dataset does not contain 3D data (use_3D_dataset=False), the data structure from the MVTec AD dataset is assumed. Both dataset structures are described in the documentation of load_img_datasets in utils.py.
