### ISSUE TITLE
average ROC at the image level only 87.27?

### ISSUE THREAD

**Issue by EWAN9709** [marco-rudolph/AST#13]
Thank you for your team's open-source code. Why is the average ROC at the image level only 87.27 on our side, which differs from the 93.7 in the paper? Did I understand it wrong?
![image](https://github.com/marco-rudolph/AST/assets/82500501/c30f9895-dcbe-49df-90f1-fbb823566cf7)
![image](https://github.com/marco-rudolph/AST/assets/82500501/fcfa93a9-d84f-4a1c-b19b-c438f08f4b03)

**Comment by marco-rudolph** [comment]
Hi,

we reported the maximum anomaly score over the spatial dimensions of the output maps which are shown in the second column of your console output (94.8%).

Best,
Marco

**Comment by EWAN9709** [comment]
Thank you for your answer. But what you mentioned in your article is misleading.
![image](https://github.com/marco-rudolph/AST/assets/82500501/12c7166f-22b6-40a7-8558-b26be2cd102e)

Best,
Ewan

**Comment by agoodge** [comment]
> Thank you for your answer. But what you mentioned in your article is misleading. ![image](https://user-images.githubusercontent.com/82500501/272441707-12c7166f-22b6-40a7-8558-b26be2cd102e.png)
> 
> Best, Ewan

I believe it is the mean/maximum value across pixel values in the anomaly score map. Not the maximum performance over the 5 runs.

**Comment by EWAN9709** [comment]
> > Thank you for your answer. But what you mentioned in your article is misleading. ![image](https://user-images.githubusercontent.com/82500501/272441707-12c7166f-22b6-40a7-8558-b26be2cd102e.png)
> > Best, Ewan
> 
> I believe it is the mean/maximum value across pixel values in the anomaly score map. Not the maximum performance over the 5 runs.

well, thanks for your answer,

**Comment by marco-rudolph** [comment]
> > Thank you for your answer. But what you mentioned in your article is misleading. ![image](https://user-images.githubusercontent.com/82500501/272441707-12c7166f-22b6-40a7-8558-b26be2cd102e.png)
> > Best, Ewan
> 
> I believe it is the mean/maximum value across pixel values in the anomaly score map. Not the maximum performance over the 5 runs.

This is true. Note that the actual numbers for the RGB+3D setting are higher than reported due to an implementation bug.

**Comment by EWAN9709** [comment]
> > > Thank you for your answer. But what you mentioned in your article is misleading. ![image](https://user-images.githubusercontent.com/82500501/272441707-12c7166f-22b6-40a7-8558-b26be2cd102e.png)
> > > Best, Ewan
> > 
> > 
> > I believe it is the mean/maximum value across pixel values in the anomaly score map. Not the maximum performance over the 5 runs.
> 
> This is true. Note that the actual numbers for the RGB+3D setting are higher than reported due to an implementation bug.

thanks for your answer!
