### ISSUE TITLE
 RuntimeWarning: invalid value encountered in float_scalars

### ISSUE THREAD

**Issue by Jay-zzcoder** [marco-rudolph/AST#15]
Thank you for excellent work! But when I run this code, I meet some bugs:
When I train teacher model, I meet this bug:  RuntimeWarning: invalid value encountered in float_scalars. The train loss is NaN.
I didn't change the code.

**Comment by marco-rudolph** [comment]
Thanks :) 
Hard to say what happened there as nobody had reported something like this before...
Have you installed the given requirements as specified?
On which data was the model trained? 
Does the error occur from the first iteration or comes after some epochs/iterations? Can you inspect from which layer the problem occurs? Is the loss or some weight diverging before?

**Comment by Jay-zzcoder** [comment]
> Thanks :) Hard to say what happened there as nobody had reported something like this before... Have you installed the given requirements as specified? On which data was the model trained? Does the error occur from the first iteration or comes after some epochs/iterations? Can you inspect from which layer the problem occurs? Is the loss or some weight diverging before?

Sorry~ Maybe I made mistakes when I preprocessed 3D data. Now I can run this code with no bugs.

**Comment by jcjlin** [comment]
> > Thanks :) Hard to say what happened there as nobody had reported something like this before... Have you installed the given requirements as specified? On which data was the model trained? Does the error occur from the first iteration or comes after some epochs/iterations? Can you inspect from which layer the problem occurs? Is the loss or some weight diverging before?
> 
> Sorry~ Maybe I made mistakes when I preprocessed 3D data. Now I can run this code with no bugs.

Hey @Jay-zzcoder  would you mind to share which part did you made mistakes while preprocessing 3D data? 
I am facing similar issues. Thanks.
