### ISSUE TITLE
Why the depth values will miss?

### ISSUE THREAD

**Issue by limaodaxia** [marco-rudolph/AST#16]
In the paper
>We discard the x and y coordinates due to the low informative content and use only the depth component z in centimeters. Missing depth values are repeatedly filled by using the average value of valid pixels

I think operation is taking the the third channel of the 3d image, why the depth values will miss?

**Comment by marco-rudolph** [comment]
We discard the x and y coordinate as they are mostly redundant as they can be inferred by its positional index map[x, y] and the depth z.

**Comment by limaodaxia** [comment]
Thank you a lot @marco-rudolph, I seldom get a reply, I am very appreciate of it.
This is the first time I've found out that  x and y coordinate can be inferred by its positional index map[x, y] and the depth z. How can we do it? In fact, I can not understand the 3D Images in the MVTec 3D AD dataset,  why it is a square tiff image such as 800 × 800? 
In ModelNet40 dataset, the point cloud is an array of point coordinate and other information just like [x, y, z, ...] (a d dimension vector )saved in a txt file. In the txt file, each line represent a point. If we have eight hundred lines, we can got a numpy array the size of which is 800 × d.

**Comment by limaodaxia** [comment]
Hi, @marco-rudolph, I am back again, 
I think a generating mask to mask loss caculation and mask lossmap when inferring is very reasonable, as you written in the paper. 

It can avoid meaningless background predictions. we do not caculate the loss where the pixel value is zero in the mask. 

But in some classes, just like bagel, the center of the picture is black, I think it is also belong to foreground, but this region does not involved in loss calculations and final predictions. 

I think it is a drawback, or maybe it a tradeoff. All in all, generating mask is a good choice.

**Comment by marco-rudolph** [comment]
> Thank you a lot @marco-rudolph, I seldom get a reply, I am very appreciate of it. This is the first time I've found out that x and y coordinate can be inferred by its positional index map[x, y] and the depth z. How can we do it? In fact, I can not understand the 3D Images in the MVTec 3D AD dataset, why it is a square tiff image such as 800 × 800? In ModelNet40 dataset, the point cloud is an array of point coordinate and other information just like [x, y, z, ...] (a d dimension vector )saved in a txt file. In the txt file, each line represent a point. If we have eight hundred lines, we can got a numpy array the size of which is 800 × d.

In the MVTec 3D dataset, the point cloud is rasterized in terms of being a grid (this is why it can be represented by an image). When indexing [x, y], you index the camera coordinates. If you would intersect the plane with depth z with the ray of the camera center to [x, y], you could calculate [x', y'] in world coordinates. For more details, please check some foundations of camera geometry.

**Comment by marco-rudolph** [comment]
> Hi, @marco-rudolph, I am back again, I think a generating mask to mask loss caculation and mask lossmap when inferring is very reasonable, as you written in the paper.
> 
> It can avoid meaningless background predictions. we do not caculate the loss where the pixel value is zero in the mask.
> 
> But in some classes, just like bagel, the center of the picture is black, I think it is also belong to foreground, but this region does not involved in loss calculations and final predictions.
> 
> I think it is a drawback, or maybe it a tradeoff. All in all, generating mask is a good choice.

We are mainly interested in existing structures which would be present in the foreground. As there is no structure in the center, I would argue that this is no big problem. On the other side, one could argue that the foreground shape could possibly not modeled perfectly.

**Comment by limaodaxia** [comment]
> > Hi, @marco-rudolph, I am back again, I think a generating mask to mask loss caculation and mask lossmap when inferring is very reasonable, as you written in the paper.
> > It can avoid meaningless background predictions. we do not caculate the loss where the pixel value is zero in the mask.
> > But in some classes, just like bagel, the center of the picture is black, I think it is also belong to foreground, but this region does not involved in loss calculations and final predictions.
> > I think it is a drawback, or maybe it a tradeoff. All in all, generating mask is a good choice.
> 
> We are mainly interested in existing structures which would be present in the foreground. As there is no structure in the center, I would argue that this is no big problem. On the other side, one could argue that the foreground shape could possibly not modeled perfectly.

Thanks for your help. Your work is inspiring.
