### ISSUE TITLE
How do you think the image-auc metric?

### ISSUE THREAD

**Issue by limaodaxia** [marco-rudolph/AST#18]
Hi, @marco-rudolph,  how do you think the metric of image-auc ?

I think the training of all kinds of Student-Teacher Network can only improve the metric of pixel-auc or pro, because the loss fuction is MSEloss between teacher's feature map and student's feature map. The loss only reflect the pixel level distance not the image level, so taking the maximum of the feature map as anomaly score may be not  reasonable. even if taking the maximum will work, i think it is occasionally.

**Comment by marco-rudolph** [comment]
Hey,
from a theoretical perspective, one could argue that taking the maximum is not an elegant way on image-level. As anomalies often occur at small spots where derivations get smoothed out by taking the average, it often makes sense to take the maximum of the error. As an alternative, experimenting with some kind of smooth maximum could bring some benefits in particular cases.

Best,
Marco

**Comment by limaodaxia** [comment]
Hey, Marco 
Your reply has been very helpful to me. I am a Chinese graduate student currently conducting independent research on industrial anomaly detection. you are just like my graduate supervisor. Thank you very much :）

Best,
Limao

**Comment by marco-rudolph** [comment]
No problem :)
