### ISSUE TITLE
How to do the experiment?

### ISSUE THREAD

**Issue by limaodaxia** [marco-rudolph/AST#19]
Hello, @marco-rudolph, I am back a again :)
I would like to ask you a question that is not related to the paper, but rather to the research process.

There are many categories in the MVTec AD and other dataset . Should we first adjust the model to a better level on one category before testing other datasets?
Have you ever encountered situations in your research where the effect is particularly good in one category but very poor in other categories, almost ineffective?

Sorry to bother you, I would appreciate it if you could reply!

**Comment by marco-rudolph** [comment]
Hi,

in general, as is common for Neural Networks, hyperparameters that work well for one dataset have a better chance of working better for other datasets. On the other hand, some datasets are harder than/different to others, so the method/hyperparameters will perform poorly. Especially for AD, the choice of the feature extractor is crucial. Of course you have a better chance to perform on a novel dataset if you have tuned your hyperparameters according to another similar dataset. Still, there are no hard rules.

Hope that helps,
Marco
