### ISSUE TITLE
network question

### ISSUE THREAD

**Issue by 0belle** [marco-rudolph/AST#2]
Hello,
I have a question about dataset, why AST work badly on dataset of cable gland、dowel and tire, I have seen dataset, but I couldn't figure it out

**Comment by marco-rudolph** [comment]
Hello,
these classes are generally quite challenging, so other methods also perform poorly there in many cases. Sometimes the anomalies are hardly visible on the 3D scans or the scans contain noise. In the case of Tire, the anomalies are sometimes difficult to recognize from the RGB images.

**Comment by 0belle** [comment]
Hello,
Thank you for your reply, and I saw that you referred to the paper 3d-ST, so I would like to ask if you have the code of this paper

**Comment by marco-rudolph** [comment]
Hi,
unfortunately, I don't have the code to this method. Afaik, the code will not be officially published by the authors for legal reasons.

Best,
Marco

**Comment by 0belle** [comment]
Hello,
Thank you for your reply, and I have a question about preprocess. The function of extract_image_features is in 2d and it extracts features from rgb images, and the function of preprocess_3D is in 3d and it  extracts 3d point clouds features, right?

**Comment by marco-rudolph** [comment]
Yes, except that "preprocess_3D" does not really extract features, it fills missing points and extracts the background.
