### ISSUE TITLE
Codes for 3D-only I-AUROC

### ISSUE THREAD

**Issue by zwandering** [marco-rudolph/AST#20]
Thanks for your excellent work!
I'm wondering if there are codes for conducting 3D-only I-AURCO experiments. Or can you briefly describe how you conduct 3D-only experiments?

**Comment by marco-rudolph** [comment]
Hey,

you can conduct 3D-only experiment by setting _mode = "depth"_ in https://github.com/marco-rudolph/AST/blob/8c243ad9adac68e874f87edc6618aa5ea2827228/config.py#L26.

Best,
Marco

**Comment by zwandering** [comment]
Thanks a lot!
