### ISSUE TITLE
question about big picture of Anomaly Detection

### ISSUE THREAD

**Issue by limaodaxia** [marco-rudolph/AST#22]
Hi, @marco-rudolph 
Good morning, I am back again. I would like to ask you some general questions
As I know, there are several method for Anomaly detection, such as Image Reconstruction, Normalize flow, Student-Teacher Network and  memory bank based (like Patchcore). The research in this field is flourishing and tends to be saturated. I want to compare Student-Teacher Networks with Memory bank based method. I think Student-Techear Network is more worth studying than memory banks, because when inference memory bank cost some memory and it will find some similar feature, so it will cost some time. On the contrary,  Student-Teacher Network directly use feature distance and do not need memory bank, so it is more efficient , Do you think my opinion is correct?

Best
Limao

**Comment by marco-rudolph** [comment]
Hi,

sorry, but this is not the right place for discussions like this. Nevertheless, I will answer it briefly.

It's hard to generally speak from better/worse methods as you may have different setups or requirements in reality - for example regarding inference time, hardness of the problem, dataset size, availability of GPUs...
Depending on the implementation and device, a memory bank may be faster than a NN pass. If you would make some assumptions, your reasoning may still apply.

Best,
Marco

**Comment by limaodaxia** [comment]
Thank you very much. I greatly ﻿appreciate it that you can reply. If you need some help, you can feel free to comment here and let me know.
