### ISSUE TITLE
print anomaly score?

### ISSUE THREAD

**Issue by danielsoy** [marco-rudolph/AST#5]
Is it possible to print the variable that holds the value of the anomaly score, of each image
at evaluation stage.

I could not find the name of such variable.
 
Thanks Marco.

**Comment by marco-rudolph** [comment]
Hi,

the scores can be found here:
https://github.com/marco-rudolph/AST/blob/47adbdce2f17ffe238a52e0bcb4c277b87652e8b/eval.py#L61
https://github.com/marco-rudolph/AST/blob/47adbdce2f17ffe238a52e0bcb4c277b87652e8b/eval.py#L62

If you want to print them for every batch, these are the lines of interest:
https://github.com/marco-rudolph/AST/blob/47adbdce2f17ffe238a52e0bcb4c277b87652e8b/eval.py#L48
https://github.com/marco-rudolph/AST/blob/47adbdce2f17ffe238a52e0bcb4c277b87652e8b/eval.py#L49

**Comment by danielsoy** [comment]
Thank u so much!
