### ISSUE TITLE
Max and mean score, which corresponds the result reported in the paper?

### ISSUE THREAD

**Issue by NoahDDavis** [marco-rudolph/AST#6]
Dear author,

As written in your code, there is max score over maps and mean score over maps, could you explain the difference, and which score did you use for the reported results in your paper?

Thanks in advance and I will appreciate it very much if you could reply.

**Comment by marco-rudolph** [comment]
Hi,

the scores are based on the map of distances between student and teacher. Either the maximum or the average over this map is taken to obtain the final score. As written in 4.2.4 of the paper, we use the maximum distance if a foreground mask is available and the average distance otherwise.

**Comment by NoahDDavis** [comment]
Got it, thanks very much for your reply!
