### ISSUE TITLE
code for pixel-level auroc?

### ISSUE THREAD

**Issue by NoahDDavis** [marco-rudolph/AST#8]
Hi, thanks for the nice work.

After browsing your code, it seems that there is no code for pixel-level auroc evaluation? (which is reported in your paper in Table 4). If there is, could you point out which part corresponds to the pixel-level auroc evaluation? 

Thanks. I would appreciate it very much if you could reply.

**Comment by marco-rudolph** [comment]
Hi,

the pixel-AUROC evaluation can now be made with the latest commit in eval.py.

Best,
Marco

**Comment by NoahDDavis** [comment]
Hi,

Thanks very much for your reply and the supplemented code. Appreciate it very much.
